# scripts/write_env_from_shell.ps1
#
# Run this script in the PowerShell session where you have set:
#   $env:R2_ACCESS_KEY_ID      = "your-key"
#   $env:R2_SECRET_ACCESS_KEY  = "your-secret"
#
# It writes a .env file in the project root that docker compose will pick up.
# The .env file is git-ignored so credentials are never committed.
#
# Usage (from the project root):
#   .\scripts\write_env_from_shell.ps1

$projectRoot = Split-Path -Parent $PSScriptRoot
$envFile = Join-Path $projectRoot ".env"

$keyId     = $env:R2_ACCESS_KEY_ID
$secretKey = $env:R2_SECRET_ACCESS_KEY

if (-not $keyId) {
    Write-Error "ERROR: `$env:R2_ACCESS_KEY_ID is not set in this shell session."
    exit 1
}
if (-not $secretKey) {
    Write-Error "ERROR: `$env:R2_SECRET_ACCESS_KEY is not set in this shell session."
    exit 1
}

$content = @"
# Auto-generated by scripts/write_env_from_shell.ps1
# Do NOT commit this file — it contains secrets.
STORAGE_BACKEND=r2
R2_ENDPOINT_URL=https://7cf52f0e0957036ef8b28411ed958be4.r2.cloudflarestorage.com
R2_BUCKET_NAME=windfarmdata
R2_ACCESS_KEY_ID=$keyId
R2_SECRET_ACCESS_KEY=$secretKey
"@

Set-Content -Path $envFile -Value $content -Encoding UTF8
Write-Host "Written: $envFile"
Write-Host "You can now run: docker compose up --build"

